### ISSUE TITLE
Enhance /api/status to set id as hostname

### ISSUE THREAD

**Issue by BondAnthony** [BondAnthony/status-service#1]
Enhance the /api/status post call to set the id as the computer hostname instead of a uuid.

Open to additional changes.

**Comment by sapanshah** [comment]
Would you like to make the hostname an optional or a required parameter? Just to clarify the user sending in the POST would be passing along the hostname correct?

**Comment by BondAnthony** [comment]
@sapanshah please make the hostname a required parameter. I originally started with a simple test and didn't circle back to making that required. We will be linking each service status to a hostname. I would like to have a UI pull that data back and group it by host when presenting the results to a user.

**Comment by sapanshah** [comment]
Cool, I updated my PR with that.
