### ISSUE TITLE
Fix UI bug undefined

### ISSUE THREAD

**Issue by BondAnthony** [BondAnthony/status-service#20]
TypeError: /home/travis/build/BondAnthony/status-service/views/status.pug:18
    16|                 strong
    17|                   span Host:
  > 18|                 span #{service.hostName}
    19|                 strong
    20|                   span Service Name:
    21|                 span=service.serviceName
Cannot read property 'hostName' of undefined
    at eval (eval at wrap (/home/travis/build/BondAnthony/status-service/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:78:64)

**Comment by jennylia** [comment]
I think my PR could address this issue

**Comment by BondAnthony** [comment]
@mstanuch Thank you for the support however a change within the status.pug resolved this issue.
