### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by BondAnthony** [BondAnthony/status-service#29]
Convert UI to React or Angular while keeping current functionality. Change color scheme to a mild blue. Include test cases where possible.

**Comment by ottoliar** [comment]
Angular 1 is fine?

**Comment by BondAnthony** [comment]
Absolutely.

**Comment by BondAnthony** [comment]
@ottoliar I actually would prefer it be written in Angular 1. One additional note, please make sure it scales correctly on a mobile devices. Go to our dev version [here](http://status-dev.cfapps.io) while on a mobile device to see the scaling problems. Let me know if you have any questions. The UI can be independent from the actual node service.

**Comment by ottoliar** [comment]
@BondAnthony Thanks. Would this include changing some of the routing in Express? For example I could put the angular script to make a request to api/status on page load and get rid of pug but that would render some of the test cases failing.

**Comment by BondAnthony** [comment]
@ottoliar that would be the right direction to head. I'll take care of the failing tests once you make the change. I could create a new branch for this work so I could assist with the service changes while your working on the UI or we can handle the changes after the PR is merged into master. 

I might make a devel branch anyway.

**Comment by BondAnthony** [comment]
I have a devel branch that will deploy directly to the development space on cloudfoundry if you want to do your work on the branch. [Dev version](http://status-dev.cfapps.io)

**Comment by BondAnthony** [comment]
@ottoliar please rebase your next PR off of the changes I've made on devel today.
