### ISSUE TITLE
Clean up the readme file so it makes sense.

### ISSUE THREAD

**Issue by BondAnthony** [BondAnthony/status-service#49]
The readme was created in a hurry by number of people. I think it's time we apply some structure to the actual file. Let's keep it basic and move the other development details into a top-level `docs` directory. We can then add a table of contents to the bottom of the readme file linking to required development details.

High-level thoughts:

- Create a `/docs` directory
- Create new readme files for development, testing, deployments
- Move required development, testing information out of the current readme.md and into the required `/docs/<topic>/readme.md`.
- Include a table of contents into the root readme.md that links to other `/docs` files.

.... Do you want to take this a step further and setup readthedocs? Go right ahead, I will help support that effort!

**Comment by divyankkarolia97** [comment]
I would like do contribute !!

**Comment by BondAnthony** [comment]
@divyankkarolia97 awesome! Please let me know if you need any help.

**Comment by khorne3** [comment]
I'd like to help as well. Spinning up readthedocs right now. :)

**Comment by BondAnthony** [comment]
@khorne3 please see if you can add webhook as a contributor..

**Comment by BondAnthony** [comment]
PR #51 moved the documentation into the `/docs` directory.

**Comment by BondAnthony** [comment]
@divyankkarolia97 could you fix the docs to be relative path instead of absolute. This would allow the docs to load locally.

**Comment by divyankkarolia97** [comment]
@BondAnthony just modified the paths, take a look at the PR.

**Comment by khorne3** [comment]
@BondAnthony No dice.

Instructions are [here](https://docs.readthedocs.io/en/latest/webhooks.html#github).

Payload URL: readthedocs.org/api/v2/webhook/status-service/15358/

**Comment by BondAnthony** [comment]
@khorne3 try again. I added the hook so you will probably need to create an event by opening a pull request and updating content that would be sent to readthedocs.

**Comment by khorne3** [comment]
Something strange is going on, @BondAnthony. The build will succeed but not generate docs. I've forked a version so I can check it out locally. Will report back when I have more.
