### ISSUE TITLE
Create a simple UI to return the results of /api/status

### ISSUE THREAD

**Issue by BondAnthony** [BondAnthony/status-service#5]
Build a clean and simple UI to present the user all the data returned by /api/status grouped by id. I'm open to a number of different UI options but a single page app would be best.

I'm leaving this up to you front-end developers to come up with a clean page to present these results. Multiple pull requests are acceptable. Please provide tests for the UI when possible.

**Comment by mooreorless** [comment]
Will work on this!

**Comment by BondAnthony** [comment]
Awesome! thank you @mooreorless

**Comment by BondAnthony** [comment]
Thanks for the support
